<a href="https://colab.research.google.com/github/Vlad-Shapar/machine-learning/blob/main/%D0%A8%D0%B0%D0%BF%D0%B0%D1%80%D1%8C_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''варіант 30'''

In [ ]:
'''Завдання 1.
Створіть одновимірний масив (вектор) з добутками квадратів кожного числа та його
подвійного значення, починаючи з 1, та виведіть його значення.'''

import numpy as np

n = 10
vector = np.arange(1, n + 1)
result = (vector ** 2) * (2 * vector)
print(result)


[   2   16   54  128  250  432  686 1024 1458 2000]


In [ ]:
'''Завдання 2
Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
коренів квадратних перших натуральних чисел.'''

import numpy as np

matrix = np.sqrt(np.arange(1, 10)).reshape(3, 3)
print(matrix)


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [ ]:
'''Завдання 3
Створіть масив розміром 5x5, заповніть його випадковими цілими числами від -10 до
10 та знайдіть кількість парних чисел. Виведіть їх.'''

import numpy as np

array = np.random.randint(-10, 11, (5, 5))
even_numbers = array[array % 2 == 0]
count_even = len(even_numbers)
print(array)
print(f"Even numbers: {even_numbers}")
print(f"Count of even numbers: {count_even}")


[[ 0  4 10  0 -1]
 [ 9 -9 -1 -7 -9]
 [ 5 -1 -3 -9  5]
 [-9  8  7 -1 -8]
 [ 0 -8 -8 -8 -9]]
Even numbers: [ 0  4 10  0  8 -8  0 -8 -8 -8]
Count of even numbers: 10


In [ ]:
'''Завдання 4
Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -1.6
до 1.6 та виведіть його значення.'''

import numpy as np

array = np.random.uniform(-1.6, 1.6, (4, 4))
print(array)


[[-1.18617775 -0.03266415  0.6139124   0.82691267]
 [-0.14826557  0.54681742 -1.25998425  1.52361038]
 [ 0.42934915 -0.8989656  -0.23670583  0.51490245]
 [ 0.55281048  0.0775399  -1.40449653 -1.35911441]]


In [ ]:
'''Завдання 5
Створіть два одновимірних масиви розміром 8, заповніть їх випадковими цілими
числами в діапазоні від 3 до 8 та виконайте на них поелементні операції додавання,
віднімання та множення'''

import numpy as np

array1 = np.random.randint(3, 9, 8)
array2 = np.random.randint(3, 9, 8)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)


Addition: [15 12 12  7 13 13  9 12]
Subtraction: [-1 -2 -4  1 -3 -3 -3  2]
Multiplication: [56 35 32 12 40 40 18 35]


In [ ]:
'''Завдання 6
Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 1 до 5 та
знайдіть їх добуток.'''

import numpy as np

matrix1 = np.random.randint(1, 6, (3, 3))
matrix2 = np.random.randint(1, 6, (3, 3))

product = np.dot(matrix1, matrix2)
print(product)


[[42 32 18]
 [38 30 16]
 [19 16  8]]


In [ ]:
'''Завдання 7
Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 10 та перемножте їх між собою.'''

import numpy as np

matrix1 = np.random.randint(1, 11, (3, 2))
matrix2 = np.random.randint(1, 11, (2, 4))

product = np.dot(matrix1, matrix2)
print(product)


[[ 74 115  75 112]
 [ 30  65  35  50]
 [ 88 140  90 134]]


In [ ]:
'''Завдання 8
Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 7 та знайдіть її обернену матрицю.'''

import numpy as np

matrix = np.random.randint(1, 8, (3, 3))
inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)

[[-0.05454545  0.29090909 -0.2       ]
 [ 0.30909091  0.01818182 -0.2       ]
 [-0.16363636 -0.12727273  0.4       ]]


In [ ]:
'''Завдання 9
Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні
від 0 до 5 та транспонуйте її.'''

import numpy as np

matrix = np.random.randint(0, 6, (5, 5))
transposed_matrix = np.transpose(matrix)
print(transposed_matrix)


[[3 4 3 2 2]
 [2 4 2 4 0]
 [3 5 4 2 2]
 [5 4 4 3 3]
 [0 4 4 1 0]]


In [ ]:
'''Завдання 10
Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть добуток матриці на вектор.'''

import numpy as np

matrix = np.random.uniform(0, 1, (3, 4))
vector = np.random.uniform(0, 1, (4, 1))

product = np.dot(matrix, vector)
print(product)


[[0.98983013]
 [1.68058775]
 [1.37857659]]


In [ ]:
'''Завдання 11
Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.'''

import numpy as np

matrix = np.random.uniform(0, 1, (2, 3))
vector = np.random.randint(1, 11, (3, 1))

product = np.dot(matrix, vector)
print(product)


[[4.69378617]
 [8.84574719]]


In [ ]:
'''Завдання 12
Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від -3 до 3 та знайдіть відношення всіх елементів другої матриці до
відповідних елементів першої матриці (поелементне ділення).'''

import numpy as np

matrix1 = np.random.randint(-3, 4, (3, 3))
matrix2 = np.random.randint(-3, 4, (3, 3))

zero_divisors = matrix1 == 0
ratio = np.divide(matrix2, matrix1, where=~zero_divisors)
ratio[zero_divisors] = np.inf

print(ratio)


[[ 1.         -0.66666667  1.        ]
 [-3.         -1.          3.        ]
 [ 0.          3.          2.        ]]


In [ ]:
'''Завдання 13
Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від -5 до 5 та знайдіть суму їх елементів.'''

import numpy as np

matrix1 = np.random.randint(-5, 6, (3, 3))
matrix2 = np.random.randint(-5, 6, (3, 3))

sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)

print("Sum of elements in matrix1:", sum_matrix1)
print("Sum of elements in matrix2:", sum_matrix2)


Sum of elements in matrix1: -3
Sum of elements in matrix2: 8


In [ ]:
'''Завдання 14
Створіть матрицю розміром 4x4, заповніть її випадковими цілими числами в діапазоні
від 1 до 10 та знайдіть кількість елементів, що дорівнюють нулю.'''

import numpy as np

matrix = np.random.randint(1, 11, (4, 4))
count_zeros = np.sum(matrix == 0)
print(matrix)
print("Number of zeros:", count_zeros)


[[ 7 10  9  9]
 [ 8  3  3  3]
 [ 6  4  8  7]
 [ 9  1  2  7]]
Number of zeros: 0


In [ ]:
'''Завдання 15
Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму кубів елементів
кожного стовпця матриці.'''

import numpy as np

matrix = np.random.uniform(-1, 1, (3, 3))
column_sums = np.sum(matrix**3, axis=0)
print("Vector of column sums of cubes:", column_sums)


Vector of column sums of cubes: [ 0.15900026 -0.74856155 -0.27136691]


**Висновок до лабораторної роботи**
У ході лабораторної роботи були виконані завдання, що включають обробку даних за допомогою бібліотеки NumPy. Було реалізовано наступні операції:

1. Створення одновимірного масиву з добутками квадратів чисел і їх подвійного значення.
2. Створення матриці 3x3 з коренями квадратними перших натуральних чисел.
3. Заповнення масиву випадковими цілими числами та підрахунок парних чисел.
4. Транспонування матриці 4x4 з випадковими дійсними числами.
5. Поелементні операції додавання, віднімання і множення над двома масивами.
6. Перемноження матриць 3x3 та матриць різних розмірів (3x2 і 2x4).
7. Знаходження оберненої матриці для випадкової матриці 3x3.
8. Транспонування матриці 5x5 і підрахунок кількості нульових елементів у матриці 4x4.
9. Множення матриці 3x4 на вектор 4x1 та матриці 2x3 на вектор 3x1.
10. Поелементне ділення двох матриць 3x3 і обчислення суми кубів елементів кожного стовпця.

Виконання цих завдань дозволило закріпити знання основних функцій бібліотеки NumPy для обробки масивів та матриць.